### PR TITLE
basic IO calls auto instrumentation

### PR DESCRIPTION
**Pull request by pdelewski**
Support for few IO calls

### CODE REVIEW

**Comment by brettmc** [comment]
Can you also add this project to the github test matrix?

**Comment by pdelewski** [comment]
> Can you also add this project to the github test matrix?

Yes, sure. I was thinking about doing that in next PR, but it makes more sense to do that in current one. BTW seems that we have to do that for PDO and Wordpress as well.

**Comment by pdelewski** [comment]
@brettmc updated `.gitsplit.yml` as well

**Review by brettmc — APPROVED** [review]
I've created the destination repo for git-split.

**Comment by pdelewski** [comment]
> I've created the destination repo for git-split.

Thank you

**Pull request merged**
