### PR TITLE
Use PSR Http Client instead of Guzzle

### PR DESCRIPTION
**Pull request by mtk3d**
My proposition to achieve the issue https://github.com/open-telemetry/opentelemetry-php/issues/565

### CODE REVIEW

**Review by brettmc — APPROVED** [review]

**Comment by brettmc** [comment]
Thankyou, this looks good. Could you please sign the CLA so that your contribution can be accepted?
Can you please check the failing action for 8.0?

**Comment by mtk3d** [comment]
Sure, it's signed now.
I will fix the failing action tomorrow.
I already investigated that there is a problem with Psalm on 8.0 which fails on `\UnitEnum` type in the `getParameter` method on the newest Symfony DependencyInjection component version.

**Comment by mtk3d** [comment]
I've tried to find the solution for this issue, but unfortunately, that is the psalm issue or more precisely the Symfony Plugin issue.
I found this issue https://github.com/vimeo/psalm/issues/7738 and there are no fixes in Psalm or Symfony Plugin yet, so at this moment the only way to fix the issue is to suppress it. I've specified the smallest part to ignore as possible so this is suppressed only in one file, only for a single class.

**Comment by tidal** [comment]
Thank you @mtk3d !

It's looking all fine now.

**Review by tidal — APPROVED** [review]

**Pull request merged**
