### PR TITLE
Update `TraceAttributes` to semconv to 1.22.0

### PR DESCRIPTION
**Pull request by julianocosta89**
After PR https://github.com/open-telemetry/opentelemetry-php/pull/1126 got merged, `HTTP_FLAVOR` was dropped and all the  instrumentations that used it started failing.

This PR updates `TraceAttributes::HTTP_FLAVOR` to `TraceAttributes::NETWORK_PROTOCOL_VERSION`.

### CODE REVIEW

**Review by brettmc — APPROVED** [review]

**Comment by brettmc** [comment]
Thanks, @julianocosta89 - I've just noticed that I only check for removed `ResourceAttributes` but not `TraceAttributes` as part of updating SemConv...
There are a few failures still, it looks like some packages are not picking up the latest SemConv version - they might need a more explicit version constraint. I think `^1.22` should do it.

**Comment by julianocosta89** [comment]
Thanks @brettmc!

It seems that there are other attributes that need to be updated, I'll take care of that

**Comment by julianocosta89** [comment]
Just one attribute that I couldn't find: `HTTP_CLIENT_IP`

I've replaced with `NET_SOCK_PEER_ADDR`, but not sure if that is correct.

**Comment by julianocosta89** [comment]
@brettmc and @pdelewski I've updated a bunch of other TraceAttributes after your review, would you mind double checking it?
Also, I'm not sure about this: https://github.com/open-telemetry/opentelemetry-php-contrib/pull/204#issuecomment-1771065608

Appreciate the help!

**Review by cedricziel — APPROVED** [review]
lgtm!

**Review by brettmc — APPROVED** [review]

**Comment by brettmc** [comment]
I've tagged new versions of the updated packages. Thanks, @julianocosta89

**Pull request merged**
